# Generated by Django 5.2.4 on 2025-07-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
