# Generated by Django 5.2.4 on 2025-07-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
