# Generated by Django 5.2.6 on 2025-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Historical', 'Historical'), ('Tale', 'Tale'), ('Philosophy', 'Philosophy'), ('Classic', 'Classic'), ('Romance', 'Romance'), ('Art', 'Art'), ('Cooking/Food', 'Cooking/Food'), ('Fantastic', 'Fantastic')], default='Classic', max_length=50),
        ),
    ]
