# Generated by Django 5.2.4 on 2025-07-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
    ]
